### PR TITLE
Keep reference to metadata before regenerating images.

### LINKED ISSUE #136: Existing images are not skipped
### Overview

`Skip regenerating existing correctly sized thumbnails (faster).` option is ignored. The images are regenerated regardless its value.

### How to reproduce
- Open the tool page and run the plugin
- Open the media directory and observed that the thumbnails are generated.
- Run the plugin a second time with the Skip option enabled.

### What I expected to happen
- The existing images to be skipped

### What happened instead
- The images are regenerated again. You can check the file dates to verify this.

### LINKED ISSUE #142: all thumbnails are deleted if "Skip regenerating existing" and "Delete thumbnail files for old unregistered sizes" are checked
I ran the plugin on 12,000+ media files (with v3.14)

I selected both 
`Skip regenerating existing correctly sized thumbnails (faster)` and `Delete thumbnail files for old unregistered sizes`

all of my thumbnails got wiped, leaving only the original images and `-scaled` versions

probably related to
https://github.com/Automattic/regenerate-thumbnails/issues/136

(note I did previously clean up my Media Library with **Media Cleaner Pro** plugin to get rid of unused files, but I don't think it should've affected this)

thanks
J

(updated to v3.15 but it isn't regenerating when using it on single images either... could be to do with theme setup I guess on where/when sizes are registered.. although they appear on the regenerate UI ok.. see screenshot)

image

### PR DESCRIPTION
**Pull request by aaronfc**
Fixes #136

## Description of the change
Starting from WP 5.3 "sizes" attribute on metadata is reset to empty when passed to `intermediate_image_sizes_advanced` filter.
The fix saves temporarily the metadata for the original file before calling the `intermediate_image_sizes_advanced` filter, so we can keep the same logic that was being applied before.

## Alternatives
I have been tempted to just remove the check for metadata sizes completely. I don't quite understand why it was introduced and doesn't seem really needed to me. But I finally decided to keep logic the same.

## Testing instructions
- Checkout to the branch.
- Run `yarn` (see detailed instructions below).
- Upload some images to the media library.
- Go to `Tools > Regenerate Thumbnails`.
- Make sure the option "Skip regenerating existing correctly sized thumbnails (faster)." is **marked**.
- Click on `Regenerate Thumbnails for ...` button.
- Check that the images are not regenerated – you can do that by going manually to the `wp-content/uploads/...` folder and checking that the file modification time does not change.

## Extra details on build step (troubleshooting)
I had some trouble setting up the development environment  – here are the details I followed:
- Open terminal using Rosetta with `arch -x86_64 zsh`.
- `nvm install v8 && nvm use v8`.
- `npm install yarn --no-save`
- `node_modules/.bin/yarn`
- `node_modules/.bin/yarn build`

### CODE REVIEW

**Comment by MarcGuay** [comment]
My understanding of the need for checking the metadata sizes is that is how we know which sizes the image is supposed to have matching files for.  Once we know what sizes we should have, then we can know which ones already have existing files and don't need to be regenerated.

**Comment by aaronfc** [comment]
> My understanding of the need for checking the metadata sizes is that is how we know which sizes the image is supposed to have matching files for. Once we know what sizes we should have, then we can know which ones already have existing files and don't need to be regenerated.

Thanks for your input, @MarcGuay. Let me develop a bit further my concern below.

If I am not missing anything, the sizes we "expect" are passed to the `intermediate_image_sizes_advanced` hook as its first parameter. Then, as you mentioned, we check the sizes in the metadata [here](https://github.com/Automattic/regenerate-thumbnails/pull/143/files#diff-de142c98932c0b339344782b50f151e60b8e2333b356bce27b8eb559013f6bcfR329-R331) and [here](https://github.com/Automattic/regenerate-thumbnails/pull/143/files#diff-de142c98932c0b339344782b50f151e60b8e2333b356bce27b8eb559013f6bcfR363-R364).

But the thing is that, we are already doing something _similar_ in the get_thumbnail method called [here](https://github.com/Automattic/regenerate-thumbnails/pull/143/files#diff-de142c98932c0b339344782b50f151e60b8e2333b356bce27b8eb559013f6bcfR348-R355). Since we are generating the filename based on the expected sizes and later it's checked if the [file_exists](https://github.com/Automattic/regenerate-thumbnails/pull/143/files#diff-de142c98932c0b339344782b50f151e60b8e2333b356bce27b8eb559013f6bcfR365).

It's not _exactly_ the same, but I see it just as an extra measure in case the file existed (with the expected image dimensions in the file name) but having different real dimensions.

Anyway, I think that explaining it out loud here made me convince that it's not that bad to keep the extra check. Thanks for commenting on it!

File: includes/class-regeneratethumbnails-regenerator.php [hunk 1]
```diff
@@ -313,7 +322,7 @@ public function filter_image_sizes_to_only_missing_thumbnails( $sizes, $fullsize
 			return $sizes;
 		}
 
-		$metadata = wp_get_attachment_metadata( $this->attachment->ID );
+		$metadata = $this->old_metadata;
```
Comment (fjorgemota) [inline includes/class-regeneratethumbnails-regenerator.php:325]: Probably a quite silly thing but, WDYT about resetting the `old_metadata` property after the `remove_filter` call for this filter? 

The reason I'm asking this is that, while the property itself is private, it keeps the internal state of the attachment being processed. Hence, if a third party for some reason decides to call this method (which it shouldn't, but oh well, people are people.. and technically better safe than sorry), then it will find unexpected results because of the internal state saved in `old_metadata`.

Based on this, my suggestion would be to just reset `old_metadata` to an empty array, and then check here if this variable is `empty`, and if it is, we just return early with the `$sizes` variable, without doing anything else.

**Review by fjorgemota — APPROVED** [review]
Looks good and works well!

I left a comment with a suggestion to improve slightly the suggestion. It is meant to protect against an use-case that technically shouldn't exist, BUT that is viable for some reason, hence the suggestion.

I'm already approving it in case you don't agree with the suggestion, though. :)

**Comment by ddur** [comment]
There is another regenerate thumbnails issue created by WP 5.3 disaster changes.
You have opportunity to fix it now.
Issue https://github.com/Automattic/regenerate-thumbnails/issues/102

**Comment by aaronfc** [comment]
> There is another regenerate thumbnails issue created by WP 5.3 disaster changes.
You have opportunity to fix it now.
Issue https://github.com/Automattic/regenerate-thumbnails/issues/102

Hey @ddur, thanks for your feedback. I would rather have the issues separated.
Hopefully we will be able to work on that one soon. Meanwhile, just a reminder that you can raise a PR yourself if you have a clear solution in mind.

File: includes/class-regeneratethumbnails-regenerator.php (hunk 1 above)
Comment (aaronfc) [reply includes/class-regeneratethumbnails-regenerator.php:325]: Hey Fernando, initially I thought it made a lot of sense. But when implementing the changes I realised that this class i already quite dependent on its internal status (like `attachment->ID`, `fullsizepath` and so on).

So for the moment I am leaving it as it is, so we don't add more complexity to the logic.

Comment (fjorgemota) [reply includes/class-regeneratethumbnails-regenerator.php:325]: Ha, very good point indeed, I didn't see that we already have a bunch of states already in the properties of the class. 

Thanks for the heads up! ;)
